### ISSUE TITLE
Assertion Failed: The options object passed to tracked() may only contain a 'value' or 'initializer' property, not both

### ISSUE THREAD

**Issue by basz** [NullVoxPopuli/ember-query-params-service#13]
`Assertion Failed: The options object passed to tracked() may only contain a 'value' or 'initializer' property, not both. Received: [descriptor,key,kind,placement,initializer,toString]`.

ember 3.11.1

controller
```
export default Controller.extend({
  // dataSource: null,
  queryParams: ['page', 'sort'],
  page: null,
  sort: null
```

route
```
import Route from '@ember/routing/route';
import { queryParam } from 'ember-query-params-service';

export default class extends Route {
  @queryParam page;
  @queryParam sort;
```

NullVoxPopuli said
> it's possible that ember-cli-babel is out of date, or that ember-query-params-service is using the wrong proposal spec

`"ember-cli-babel": "^7.7.3",`

**Comment by basz** [comment]
After upgrading to ember 3.13.0-beta.5 this issue still exists...

**Comment by NullVoxPopuli** [comment]
Hi! thanks for the issue report!

It's totally possible that there is an issue with interop with the ember's query param handling here. 
A reproduction PR would be immensely helpful <3

**Comment by basz** [comment]
Been a while since I’ve seen this. Can remember now... not an issue anymore... 
thank you for getting back to this though
