### ISSUE TITLE
Proposal for query param default value

### ISSUE THREAD

**Issue by cah-briangantzler** [NullVoxPopuli/ember-query-params-service#367]
As currently implemented, the default value is more an initial value. I would like the query params to treat the default value as a more true default value. If the current value is the default value, the query param should not appear on the URL.

Proposed implementation
```
@queryParam({
   defaultValue: true
})
```

allow setting the default value in the same options hash that the serialize/deserialize use.

Notes: 
    ~~The default value is set as a string as it may make it easier in the code. While writing the code this may be removed and allow for just the value true~~. Code does support native values
    The default value may not easily be set dynamically. When writing the code will see what can be done about this.

**Comment by cah-briangantzler** [comment]
Thanks for merging that but I do have one question, you changed the line here https://github.com/NullVoxPopuli/ember-query-params-service/blob/master/addon/utils/query-param/helpers.ts#L6 for the type from `any` to `string`. The reason I had `any` was for booleans and numbers, but also if the user implemented a serialize deserialize, the default could even be an `object` or anything.   In the tests I actually use booleans https://github.com/NullVoxPopuli/ember-query-params-service/blob/master/tests/unit/utils/query-param-test.ts#L207 and numbers https://github.com/NullVoxPopuli/ember-query-params-service/blob/master/tests/unit/utils/query-param-test.ts#L261 and this is not a string, why isnt an error thrown since you changed the type to `string`.   There may be some auto-boxing going on. 

But given a complex serialize/deserialize I think string is limiting.    I would think the default value should be the actual default value, not the string representation of the of the serialized value. Thats why above its `{ defaultValue: false }` and not `{ defaultValue: 'false' }`.  putting quotes around the default value seemed wrong for the consumer to have to know.

**Comment by NullVoxPopuli** [comment]
i agree!
