### ISSUE TITLE
Proposal for stickyness

### ISSUE THREAD

**Issue by cah-brian-gantzler** [NullVoxPopuli/ember-query-params-service#371]
By default all the params are sticky. Provide for an option to specify if a param should not be sticky. 

Add an option (default to true if not specified)
```
{
   sticky: false
}
```

Create a method on the service
```
 reset(path);
 resetAll(path);
```

`reset` would set all the parameters on the passed path (current if no path passed) that are marked as sticky = false to their default values (undefined if no default value specified).

`resetAll` would set all the parameters on the passed path (current if no path passed) to their default values.

These methods would be called from somewhere on the controller, most likely [resetController](https://api.emberjs.com/ember/release/classes/Route/methods?anchor=resetController). At this time the consumer would have to opt in to actually creating the resetController hook and calling the reset method. Can look in the future for possibly making this an automatic call for all controllers.

Thoughts?

**Comment by NullVoxPopuli** [comment]
any additional thoughts?

Just realized, it's been a while. :sweat_smile:

**Comment by cah-brian-gantzler** [comment]
Re-thinking my use of this addon and my understanding of query params. Closing this. Will re-open a new issue if I find I need one.
