### ISSUE TITLE
Suggestion: Should the query params be sorted when added to the URL

### ISSUE THREAD

**Issue by cah-briangantzler** [NullVoxPopuli/ember-query-params-service#401]
As I was messing with query params the new ones I added were at the end of the URL, I was wondering if we should sort them prior to adding them the to the url for consistency. Ember Data does this so they are always in the same order for browser to see they have been previous cached. Different problem but for consumer reading, just wondered.

Any thoughts?

We add out query params to existing in some cases, I would assume we should sort the existing into ours rather than leave them seperate

**Comment by NullVoxPopuli** [comment]
oh I like that idea -- would make testing a smidge easier, perhaps?

**Comment by cah-briangantzler** [comment]
K, ill work on a PR for that
