### ISSUE TITLE
Weirdness of this decorator. Just some thoughts

### ISSUE THREAD

**Issue by cah-brian-gantzler** [NullVoxPopuli/ember-query-params-service#405]
Previous there was code like this
```
@queryParam a = 1;
```
Which set the value the initial value to one, not really the default value in terms of query params.

Now we have this
```
@queryParam({defaultValue: 1}) a;
```
But if you were to do this
```
@queryParam({defaultValue: 1}) a = 2;
```
A doesnt get set to 2, because of the way default value works. I dont think you would ever really do this as it kinda defeats the purpose of the default. Think we are ok there. 

Now you could do this 
```
@queryParam({defaultValue: 1}) a;

constructor() {
   super(...arguments);
   this.a = 2;
}
```
And that actually works, a is 2, because the QueryParamHandler.set got called. This however only works in a component. If you put the above code in a controller for a child route (not application as you have in the dummy app), things get weird. The application is currently showing the root path of / but ember is pre instantiating controllers since they are singletons which means the controller constructor gets fired when the wrong route than intended is current. (Does that make sense?) The gotcha is dont set query param values in the constructor of a controller (or specifically singleton. ie what if someone uses this decorator in a service or a route )

The decorator as designed is not tied to a specific route at all, its what ever is current. We should probably make this a lot more clear in the read me to help avoid this nuances.

Just talking now, not purposing....   If we switch to route name instead of path, I guess we could add a routeName to the options, then only set if that route is the current route, what about get, defaultValue or maybe undefined if correct route isnt current.  Solves problems but causes a maintenance problem. The decorator is re-run every time the component is on the screen so we could do some things there, but only run once on singletons so wouldnt work all the time. 

Just some thoughts.  Any comments?

**Comment by NullVoxPopuli** [comment]
I agree that the README could use some updating and that semantics of defaultValue + assignment are a bit awkward, and I'm willing to work though some iteration on that.

I don't think we should be setting properties in the constructor (ever), unless they aren't tracked-like properties.

Re: path vs route, let's keep that discussion here: https://github.com/NullVoxPopuli/ember-query-params-service/issues/398#issuecomment-970730926

**Comment by cah-brian-gantzler** [comment]
This is really old, we did talk about it. Should prob just close.
