### ISSUE TITLE
Replace + with spaces, as mentioned in the spec

### ISSUE THREAD

**Issue by BoussonKarel** [NullVoxPopuli/ember-query-params-service#481]

**Comment by NullVoxPopuli** [comment]
I finally got around to doing some maintenance on this repo and released a new version (as a v2 addon, and basically no other changes).

Any chance you can create a failing test that describes the desired behavior? thank you!!

**Comment by BoussonKarel** [comment]
Looks like an old issue, it works so I'm closing it
